version: "3"

services:
  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
  redis:
    image: redis:alpine
    expose:
      - 6379
